# Generated by Django 3.2.6 on 2021-11-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='user_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tags',
            name='user_Id',
            field=models.IntegerField(),
        ),
    ]
