# Generated by Django 3.2.6 on 2021-11-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_actor_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='Actor_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='director',
            name='Director_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='genome_tags',
            name='tag',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=300),
        ),
    ]
