# Generated by Django 3.2.6 on 2021-11-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211108_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieImages',
            new_name='Movie_Images',
        ),
    ]
