# Generated by Django 3.2.6 on 2021-11-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_movieimages_movie_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='imdb_movie_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.movies'),
        ),
    ]
