# Generated by Django 3.2.6 on 2021-11-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_links_imdb_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='imdb_movie_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movies'),
        ),
    ]
