# Generated by Django 3.2.6 on 2021-11-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Happy', models.FloatField()),
                ('Angry', models.FloatField()),
                ('Surprise', models.FloatField()),
                ('Sad', models.FloatField()),
                ('Fear', models.FloatField()),
            ],
        ),
    ]
