# Generated by Django 3.2.8 on 2021-11-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='imdb_movie_Id',
            field=models.ForeignKey(db_column='imdb_movie_Id', on_delete=django.db.models.deletion.CASCADE, to='mainhome.movies'),
        ),
    ]
