# Generated by Django 3.2.6 on 2021-11-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_like_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.IntegerField()),
                ('user_movie', models.IntegerField()),
            ],
        ),
    ]
